In [1]:
import requests, random, time
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

# Data Collection

In [77]:
url0 = 'https://www.espncricinfo.com'
url1 = 'https://www.espncricinfo.com/series/ipl-2026-1510719/match-schedule-fixtures-and-results'

user_agents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.140 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.2365.66",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.2210.91",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13.3; rv:124.0) Gecko/20100101 Firefox/124.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
    "Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36",
    "Mozilla/5.0 (Linux; Android 12; Samsung Galaxy S21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (iPad; CPU OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15",
]

headers = {
    'authority': url1,
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'accept-language': 'en-US,en;q=0.9',
    'cache-control': 'no-cache',
    'dnt': '1',
    'pragma': 'no-cache',
    'referer': url1,
    'sec-ch-ua': '"Chromium";v="107", "Not;A=Brand";v="8"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'user-agent': user_agents[0],
}

In [16]:
# 2026 ipl
d1 = requests.get(url1)

In [17]:
print(str(d1.content))

b'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;www&#46;espncricinfo&#46;com&#47;series&#47;ipl&#45;2026&#45;1510719&#47;match&#45;schedule&#45;fixtures&#45;and&#45;results" on this server.<P>\nReference&#32;&#35;18&#46;c58c2c31&#46;1780559675&#46;3a3472e\n<P>https&#58;&#47;&#47;errors&#46;edgesuite&#46;net&#47;18&#46;c58c2c31&#46;1780559675&#46;3a3472e</P>\n</BODY>\n</HTML>\n'

In [28]:
service = Service('C:/Users/shiva/Downloads/FILES/webdriver/chromedriver-win64/chromedriver.exe')
chrome_options = Options()
chrome_options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36")

driver = webdriver.Chrome(options=chrome_options, service=service)
driver.get(url1)
time.sleep(10)
htmlPage = driver.page_source
print(driver.title)

driver.close()

IPL 2026 Schedule | IPL 2026 Fixtures, Match Timings & Next Matches

In [51]:
soup = BeautifulSoup(htmlPage, "html.parser")

In [ ]:
# print(soup.prettify())

In [33]:
d = {}

In [60]:
d['link'] = soup.find('div', class_="ds-p-0").find_all('a', class_='ds-no-tap-higlight')

In [ ]:
d['link'][0].get_attribute_list('href')[0]
# /match-impact-player

'/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-sunrisers-hyderabad-1st-match-1527674/full-scorecard'

In [ ]:
service = Service('C:/Users/shiva/Downloads/FILES/webdriver/chromedriver-win64/chromedriver.exe')
chrome_options = Options()
chrome_options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36")

driver = webdriver.Chrome(options=chrome_options, service=service)
# _ - already done
i = 0
for link in d['link']:
    sleep_time1 = random.uniform(5, 10)
    sleep_time2 = random.uniform(10, 25)

    try:
        url = url0 + link.get_attribute_list('href')[0]
        driver.get(url)

        # scroll like a user
        time.sleep(random.uniform(2, 5))
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight/2);")

        time.sleep(random.uniform(2, 5))
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

        time.sleep(sleep_time1)

        htmlPage = driver.page_source
        i+= 1
        print(i)

        soup = BeautifulSoup(htmlPage, "html.parser")
        with open(f"data/{i}_s.html", "w", encoding="utf-8") as f:
            f.write(soup.prettify())

        time.sleep(sleep_time2)
        if i % 10 == 0:
            print("Cooling down...")
            time.sleep(random.uniform(60, 120))
    except Exception as e:
        print(f"Error on page {i} and {link}: {e}")
        time.sleep(30)

driver.quit()

1
2
3
4
5
6
7
8
9
10
Cooling down...
11
12
13
14
15
16
17
18
19
20
Cooling down...
21
22
23
24
25
26
27
28
29
30
Cooling down...
31
32
33
34
35
36
37
38
39
40
Cooling down...
41
42
43
44
45
46
47
48
49
50
Cooling down...
51
52
53
54
55
56
57
58
59
60
Cooling down...
61
62
63
64
65
66
67
68
69
70
Cooling down...
71
72
73
74

In [78]:
url0 + d['link'][0].get_attribute_list('href')[0]

'https://www.espncricinfo.com/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-sunrisers-hyderabad-1st-match-1527674/full-scorecard'

In [ ]:
l = []
for link in d['link']:
    l.append(link.get_attribute_list('href')[0])

d['link'] = l

In [91]:
url0 + d['link'][0].replace('full-scorecard', 'match-impact-player')

'https://www.espncricinfo.com/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-sunrisers-hyderabad-1st-match-1527674/match-impact-player'

In [ ]:
print(url0)
for link in d['link']:
    print(link.replace('full-scorecard', 'match-impact-player'))

https://www.espncricinfo.com
/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-sunrisers-hyderabad-1st-match-1527674/match-impact-player
/series/ipl-2026-1510719/mumbai-indians-vs-kolkata-knight-riders-2nd-match-1527675/match-impact-player
/series/ipl-2026-1510719/rajasthan-royals-vs-chennai-super-kings-3rd-match-1527676/match-impact-player
/series/ipl-2026-1510719/punjab-kings-vs-gujarat-titans-4th-match-1527677/match-impact-player
/series/ipl-2026-1510719/lucknow-super-giants-vs-delhi-capitals-5th-match-1527678/match-impact-player
/series/ipl-2026-1510719/kolkata-knight-riders-vs-sunrisers-hyderabad-6th-match-1527679/match-impact-player
/series/ipl-2026-1510719/chennai-super-kings-vs-punjab-kings-7th-match-1527680/match-impact-player
/series/ipl-2026-1510719/delhi-capitals-vs-mumbai-indians-8th-match-1527681/match-impact-player
/series/ipl-2026-1510719/gujarat-titans-vs-rajasthan-royals-9th-match-1527682/match-impact-player
/series/ipl-2026-1510719/sunrisers-hyderabad-vs-lucknow-super-giants-10th-match-1527683/match-impact-player
/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-chennai-super-kings-11th-match-1527684/match-impact-player
/series/ipl-2026-1510719/kolkata-knight-riders-vs-punjab-kings-12th-match-1527685/match-impact-player
/series/ipl-2026-1510719/rajasthan-royals-vs-mumbai-indians-13th-match-1527686/match-impact-player
/series/ipl-2026-1510719/delhi-capitals-vs-gujarat-titans-14th-match-1527687/match-impact-player
/series/ipl-2026-1510719/kolkata-knight-riders-vs-lucknow-super-giants-15th-match-1527688/match-impact-player
/series/ipl-2026-1510719/rajasthan-royals-vs-royal-challengers-bengaluru-16th-match-1527689/match-impact-player
/series/ipl-2026-1510719/punjab-kings-vs-sunrisers-hyderabad-17th-match-1527690/match-impact-player
/series/ipl-2026-1510719/chennai-super-kings-vs-delhi-capitals-18th-match-1527691/match-impact-player
/series/ipl-2026-1510719/lucknow-super-giants-vs-gujarat-titans-19th-match-1527692/match-impact-player
/series/ipl-2026-1510719/mumbai-indians-vs-royal-challengers-bengaluru-20th-match-1527693/match-impact-player
/series/ipl-2026-1510719/sunrisers-hyderabad-vs-rajasthan-royals-21st-match-1529264/match-impact-player
/series/ipl-2026-1510719/chennai-super-kings-vs-kolkata-knight-riders-22nd-match-1529265/match-impact-player
/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-lucknow-super-giants-23rd-match-1529266/match-impact-player
/series/ipl-2026-1510719/mumbai-indians-vs-punjab-kings-24th-match-1529267/match-impact-player
/series/ipl-2026-1510719/gujarat-titans-vs-kolkata-knight-riders-25th-match-1529268/match-impact-player
/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-delhi-capitals-26th-match-1529269/match-impact-player
/series/ipl-2026-1510719/sunrisers-hyderabad-vs-chennai-super-kings-27th-match-1529270/match-impact-player
/series/ipl-2026-1510719/kolkata-knight-riders-vs-rajasthan-royals-28th-match-1529271/match-impact-player
/series/ipl-2026-1510719/punjab-kings-vs-lucknow-super-giants-29th-match-1529272/match-impact-player
/series/ipl-2026-1510719/gujarat-titans-vs-mumbai-indians-30th-match-1529273/match-impact-player
/series/ipl-2026-1510719/sunrisers-hyderabad-vs-delhi-capitals-31st-match-1529274/match-impact-player
/series/ipl-2026-1510719/lucknow-super-giants-vs-rajasthan-royals-32nd-match-1529275/match-impact-player
/series/ipl-2026-1510719/mumbai-indians-vs-chennai-super-kings-33rd-match-1529276/match-impact-player
/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-gujarat-titans-34th-match-1529277/match-impact-player
/series/ipl-2026-1510719/delhi-capitals-vs-punjab-kings-35th-match-1529278/match-impact-player
/series/ipl-2026-1510719/rajasthan-royals-vs-sunrisers-hyderabad-36th-match-1529279/match-impact-player
/series/ipl-2026-1510719/chennai-super-kings-vs-gujarat-titans-37th-match-1529280/match-impact-player
/series/ipl-2026-1510719/lucknow-super-giants-vs-kolkata-knight-riders-38th-match-1529281/match-impact-player
/series/ipl-2026-1510719/delhi-capitals-vs-royal-challengers-bengaluru-39th-match-1529282/match-impact-player
/series/ipl-2026-1510719/punjab-kings-vs-rajasthan-royals-40th-match-1529283/match-impact-player
/series/ipl-2026-1510719/mumbai-indians-vs-sunrisers-hyderabad-41st-match-1529284/match-impact-player
/series/ipl-2026-1510719/gujarat-titans-vs-royal-challengers-bengaluru-42nd-match-1529285/match-impact-player
/series/ipl-2026-1510719/rajasthan-royals-vs-delhi-capitals-43rd-match-1529286/match-impact-player
/series/ipl-2026-1510719/chennai-super-kings-vs-mumbai-indians-44th-match-1529287/match-impact-player
/series/ipl-2026-1510719/sunrisers-hyderabad-vs-kolkata-knight-riders-45th-match-1529288/match-impact-player
/series/ipl-2026-1510719/gujarat-titans-vs-punjab-kings-46th-match-1529289/match-impact-player
/series/ipl-2026-1510719/mumbai-indians-vs-lucknow-super-giants-47th-match-1529290/match-impact-player
/series/ipl-2026-1510719/delhi-capitals-vs-chennai-super-kings-48th-match-1529291/match-impact-player
/series/ipl-2026-1510719/sunrisers-hyderabad-vs-punjab-kings-49th-match-1529292/match-impact-player
/series/ipl-2026-1510719/lucknow-super-giants-vs-royal-challengers-bengaluru-50th-match-1529293/match-impact-player
/series/ipl-2026-1510719/delhi-capitals-vs-kolkata-knight-riders-51st-match-1529294/match-impact-player
/series/ipl-2026-1510719/rajasthan-royals-vs-gujarat-titans-52nd-match-1529295/match-impact-player
/series/ipl-2026-1510719/chennai-super-kings-vs-lucknow-super-giants-53rd-match-1529296/match-impact-player
/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-mumbai-indians-54th-match-1529297/match-impact-player
/series/ipl-2026-1510719/punjab-kings-vs-delhi-capitals-55th-match-1529298/match-impact-player
/series/ipl-2026-1510719/gujarat-titans-vs-sunrisers-hyderabad-56th-match-1529299/match-impact-player
/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-kolkata-knight-riders-57th-match-1529300/match-impact-player
/series/ipl-2026-1510719/punjab-kings-vs-mumbai-indians-58th-match-1529301/match-impact-player
/series/ipl-2026-1510719/lucknow-super-giants-vs-chennai-super-kings-59th-match-1529302/match-impact-player
/series/ipl-2026-1510719/kolkata-knight-riders-vs-gujarat-titans-60th-match-1529303/match-impact-player
/series/ipl-2026-1510719/punjab-kings-vs-royal-challengers-bengaluru-61st-match-1529304/match-impact-player
/series/ipl-2026-1510719/delhi-capitals-vs-rajasthan-royals-62nd-match-1529305/match-impact-player
/series/ipl-2026-1510719/chennai-super-kings-vs-sunrisers-hyderabad-63rd-match-1529306/match-impact-player
/series/ipl-2026-1510719/rajasthan-royals-vs-lucknow-super-giants-64th-match-1529307/match-impact-player
/series/ipl-2026-1510719/kolkata-knight-riders-vs-mumbai-indians-65th-match-1529308/match-impact-player
/series/ipl-2026-1510719/gujarat-titans-vs-chennai-super-kings-66th-match-1529309/match-impact-player
/series/ipl-2026-1510719/sunrisers-hyderabad-vs-royal-challengers-bengaluru-67th-match-1529310/match-impact-player
/series/ipl-2026-1510719/lucknow-super-giants-vs-punjab-kings-68th-match-1529311/match-impact-player
/series/ipl-2026-1510719/mumbai-indians-vs-rajasthan-royals-69th-match-1529312/match-impact-player
/series/ipl-2026-1510719/kolkata-knight-riders-vs-delhi-capitals-70th-match-1529313/match-impact-player
/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-gujarat-titans-qualifier-1-1535462/match-impact-player
/series/ipl-2026-1510719/rajasthan-royals-vs-sunrisers-hyderabad-eliminator-1535463/match-impact-player
/series/ipl-2026-1510719/gujarat-titans-vs-rajasthan-royals-qualifier-2-1535464/match-impact-player
/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-gujarat-titans-final-1535465/match-impact-player

In [93]:
service = Service('C:/Users/shiva/Downloads/FILES/webdriver/chromedriver-win64/chromedriver.exe')
chrome_options = Options()
chrome_options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36")

driver = webdriver.Chrome(options=chrome_options, service=service)
# _ - already done
i = 0
for link in d['link']:
    sleep_time1 = random.uniform(5, 10)
    sleep_time2 = random.uniform(10, 25)

    try:
        url = url0 + link.replace('full-scorecard', 'match-impact-player')
        driver.get(url)

        # scroll like a user
        time.sleep(random.uniform(2, 5))
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight/2);")

        time.sleep(random.uniform(2, 5))
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

        time.sleep(sleep_time1)

        htmlPage = driver.page_source
        i+= 1
        print(i)

        soup = BeautifulSoup(htmlPage, "html.parser")
        with open(f"data/{i}_m.html", "w", encoding="utf-8") as f:
            f.write(soup.prettify())

        time.sleep(sleep_time2)
        if i % 10 == 0:
            print("Cooling down...")
            time.sleep(random.uniform(60, 120))
    except Exception as e:
        print(f"Error on page {i} and {link}: {e}")
        time.sleep(30)

driver.quit()

1
2
3
4
5
6
7
8
9
10
Cooling down...
11
12
13
14
15
16
17
18
19
20
Cooling down...
21
22
23
24
25
26
27
28
29
30
Cooling down...
31
32
33
34
35
36
37
38
39
40
Cooling down...
41
42
43
44
45
46
47
48
49
50
Cooling down...
51
52
53
54
55
56
57
58
59
60
Cooling down...
61
62
63
64
65
66
67
68
69
70
Cooling down...
71
72
73
74

In [ ]:
with open("data/main.html", "w", encoding="utf-8") as f:
    f.write(soup.prettify())

# Data Retriving

In [ ]:
with open('data/12_s.html', 'r', encoding="utf-8") as f:
    score = BeautifulSoup(f, "html.parser")
with open('data/12_m.html', 'r', encoding="utf-8") as f:
    most = BeautifulSoup(f, "html.parser")

In [29]:
' '.join(score.find('div', class_='ds-text-body-3 ds-font-medium ds-text-color-text-secondary ds-mt-1').text.strip().split())

'12th Match (N), Eden Gardens, April 06, 2026 , Indian Premier League'

In [30]:
for child in score.find('div', class_='ds-px-0 ds-border-b ds-border-color-border-secondary').children:

    if 'Match days' in child.text:
        print(' '.join(child.find('span', class_='ds-text-link-3 ds-font-medium ds-text-color-text ds-p-3').text.strip().split()))

    if 'Ground' in child.text:
        print(child.find('span', class_='ds-text-link-3 ds-font-medium ds-block ds-text-color-text ds-underline ds-decoration-color-text-tertiary hover:ds-text-color-primary hover:ds-decoration-color-primary').text.strip())
    
    if 'Player Of The Match' in child.text:
        print(child.find('span', class_='ds-text-link-3 ds-font-medium ds-block ds-underline ds-decoration-color-text-tertiary hover: hover:ds-decoration-color-primary ds-text-color-text').text.strip())

Eden Gardens, Kolkata
6 April 2026 - night (20-over match)

In [31]:
teams = score.find('div', class_='ds-flex ds-flex-col ds-mt-3 md:ds-mt-0 ds-mt-0 ds-mb-4 ds-gap-3').find_all('span', attrs={'class':'ds-text-header-5 ds-font-semibold ds-block ds-text-color-text hover:ds-text-color-primary ds-truncate'})
list(map(lambda x: x.text.strip(), teams))

['KKR', 'PBKS']

In [32]:
score.find('p', class_='ds-text-body-1 ds-font-medium ds-truncate ds-text-color-primary').find('span').text.strip()

'No result'

In [33]:
table = most.find('div', class_='ds-w-full ds-bg-fill-content-prime ds-overflow-hidden ds-rounded-xl ds-border ds-border-line').find('table', class_='ds-w-full ds-table ds-table-md ds-table-auto')

In [34]:
def table_to_df(table):
    columns = table.find('thead').find('tr').find_all('th')
    columns = list(map(lambda x:x.text.strip(), columns))

    rows = []
    for row in table.find('tbody').find_all('tr'):
        r = row.find_all('td')
        r = list(map(lambda x:x.text.strip(), r))
        rows.append(r)

    return pd.DataFrame(rows, columns=columns)

In [35]:
df = table_to_df(table)

In [217]:
df.head()

,Player,Team,TI,Runs,I. Runs,B. Impact,Bowl,I. Wkts,Bo. Impact
0,Madhav Tiwari,DC,82.04,18(8),21.58,24.32,2/40,2.53,57.72
1,Axar Patel,DC,74.5,56(30),66.78,74.5,-,-,-
2,David Miller,DC,61.36,51(28),57.42,61.36,-,-,-
3,Mukesh Kumar,DC,49.54,-,-,-,1/31,1.33,49.54
4,Arshdeep Singh,PBKS,48.34,-,-,-,2/21,3.36,48.34

In [36]:
df['TI'].sort_values().str.replace(' ', '').replace('-', np.nan).astype('float')

10      NaN
19      NaN
18      NaN
17      NaN
16      NaN
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN
20      NaN
11      NaN
12      NaN
13      NaN
14      NaN
15      NaN
21    -4.65
4      2.45
0     34.82
3      7.85
2      8.70
1      8.82
Name: TI, dtype: float64

In [37]:
df['TI'] = df['TI'].str.replace(' ', '').replace('-', np.nan).astype('float')

In [38]:
df.sort_values(['TI'], ascending=False).iloc[0]['Player']

'Xavier Bartlett'

In [39]:
df.sort_values(['TI'], ascending=False).iloc[0]['TI']

np.float64(34.82)

In [40]:
df['Runs'] = df['Runs'].str.split('(').map(lambda x : x[0]).replace('-', np.nan).astype('float')

In [41]:
df.sort_values(['Runs'], ascending=False).iloc[0]['Player']

'Ajinkya Rahane'

In [42]:
df.sort_values(['Runs'], ascending=False).iloc[0]['Runs']

np.float64(8.0)

In [231]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Player      24 non-null     object
 1   Team        24 non-null     object
 2   TI          23 non-null     float64
 3   Runs        16 non-null     float64
 4   I. Runs     24 non-null     object
 5   B. Impact   24 non-null     object
 6   Bowl        24 non-null     object
 7   I. Wkts     24 non-null     object
 8   Bo. Impact  24 non-null     object
dtypes: float64(2), object(7)
memory usage: 1.8+ KB

# DataFrame

In [ ]:
l = []
for i in range(1,75):
    with open(f'data/{i}_s.html', 'r', encoding="utf-8") as f:
        score = BeautifulSoup(f, "html.parser")
    with open(f'data/{i}_m.html', 'r', encoding="utf-8") as g:
        most = BeautifulSoup(g, "html.parser")
    
    for child in score.find('div', class_='ds-px-0 ds-border-b ds-border-color-border-secondary').children:
        if 'Player Of The Match' in child.text:
            pom = child.find('span', class_='ds-text-link-3 ds-font-medium ds-block ds-underline ds-decoration-color-text-tertiary hover: hover:ds-decoration-color-primary ds-text-color-text').text.strip()
            l.append((i, pom))
            # print(i, ': ', child.find('span', class_='ds-text-link-3 ds-font-medium ds-block ds-underline ds-decoration-color-text-tertiary hover: hover:ds-decoration-color-primary ds-text-color-text').text.strip())

In [ ]:
num = 0
for i,j in l:
    num += 1
    if i != num:
        print(num)
        break
# 12th match happend at 6th apr between kkr and pbks abandoned without a result due to heavy rain and a wet outfield.

12

In [44]:
d = {
    'Match_no': [],
    'Date': [],
    'Team1': [],
    'Team2': [],
    'Venue':[],
    'Winning_team': [],
    'Player_of_match': [],
    'Player_of_match_total_impact':[],
    'Top_scorer':[],
    'Top_scorer_runs':[],
}

In [45]:
def table_to_df(table):
    columns = table.find('thead').find('tr').find_all('th')
    columns = list(map(lambda x:x.text.strip(), columns))

    rows = []
    for row in table.find('tbody').find_all('tr'):
        r = row.find_all('td')
        r = list(map(lambda x:x.text.strip(), r))
        rows.append(r)

    return pd.DataFrame(rows, columns=columns)

In [ ]:
for i in range(1,75):
    print(i)
    with open(f'data/{i}_s.html', 'r', encoding="utf-8") as f:
        score = BeautifulSoup(f)
    with open(f'data/{i}_m.html', 'r', encoding="utf-8") as g:
        most = BeautifulSoup(g)
    
    d['Match_no'].append(' '.join(score.find('div', class_='ds-text-body-3 ds-font-medium ds-text-color-text-secondary ds-mt-1').text.strip().split()))

    for child in score.find('div', class_='ds-px-0 ds-border-b ds-border-color-border-secondary').children:
        if 'Match days' in child.text:
            d['Date'].append(' '.join(child.find('span', class_='ds-text-link-3 ds-font-medium ds-text-color-text ds-p-3').text.strip().split()))

        if 'Ground' in child.text:
            d['Venue'].append(child.find('span', class_='ds-text-link-3 ds-font-medium ds-block ds-text-color-text ds-underline ds-decoration-color-text-tertiary hover:ds-text-color-primary hover:ds-decoration-color-primary').text.strip())
        
        # if 'Player Of The Match' in child.text:
        #     d['Player_of_match'].append(child.find('span', class_='ds-text-link-3 ds-font-medium ds-block ds-underline ds-decoration-color-text-tertiary hover: hover:ds-decoration-color-primary ds-text-color-text').text.strip())

    teams = score.find('div', class_='ds-flex ds-flex-col ds-mt-3 md:ds-mt-0 ds-mt-0 ds-mb-4 ds-gap-3').find_all('span', attrs={'class':'ds-text-header-5 ds-font-semibold ds-block ds-text-color-text hover:ds-text-color-primary ds-truncate'})
    teams = list(map(lambda x: x.text.strip(), teams))
    d['Team1'].append(teams[0])
    d['Team2'].append(teams[1])

    d['Winning_team'].append(score.find('p', class_='ds-text-body-1 ds-font-medium ds-truncate ds-text-color-primary').find('span').text.strip())

    table = most.find('div', class_='ds-w-full ds-bg-fill-content-prime ds-overflow-hidden ds-rounded-xl ds-border ds-border-line').find('table', class_='ds-w-full ds-table ds-table-md ds-table-auto')
    df = table_to_df(table)
    df['TI'] = df['TI'].str.replace(' ', '').replace('-', np.nan).astype('float')
    df['Runs'] = df['Runs'].str.split('(').map(lambda x : x[0]).replace('-', np.nan).astype('float')
    
    d['Player_of_match'].append(df.sort_values(['TI'], ascending=False).iloc[0]['Player'])
    d['Player_of_match_total_impact'].append(df.sort_values(['TI'], ascending=False).iloc[0]['TI'])
    d['Top_scorer'].append(df.sort_values(['Runs'], ascending=False).iloc[0]['Player'])
    d['Top_scorer_runs'].append(df.sort_values(['Runs'], ascending=False).iloc[0]['Runs'])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74

In [ ]:
for keys, values in d.items():
    print(keys, ':', len(values))

Match_no : 74
Date : 74
Team1 : 74
Team2 : 74
Venue : 74
Winning_team : 74
Player_of_match : 74
Player_of_match_total_impact : 74
Top_scorer : 74
Top_scorer_runs : 74

In [82]:
df = pd.DataFrame(d)

In [ ]:
# df = pd.read_csv('match_data.csv')

In [22]:
df.tail()

,Match_no,Date,Team1,Team2,Venue,Winning_team,Player_of_match,Player_of_match_total_impact,Top_scorer,Top_scorer_runs
69,70th Match,2026-05-24,DC,KKR,"Eden Gardens, Kolkata",DC,Kuldeep Yadav,91.99,Ajinkya Rahane,63.0
70,Qualifier 1,2026-05-26,RCB,GT,"Himachal Pradesh Cricket Association Stadium, ...",RCB,Rajat Patidar,110.94,Rajat Patidar,93.0
71,Eliminator,2026-05-27,RR,SRH,Maharaja Yadavindra Singh International Cricke...,RR,Vaibhav Sooryavanshi,198.38,Vaibhav Sooryavanshi,97.0
72,Qualifier 2,2026-05-29,RR,GT,Maharaja Yadavindra Singh International Cricke...,GT,Shubman Gill,109.62,Shubman Gill,104.0
73,Final,2026-05-31,GT,RCB,"Narendra Modi Stadium, Ahmedabad",RCB,Virat Kohli,91.76,Virat Kohli,75.0

In [7]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [9]:
df['Match_no'] = df['Match_no'].str.split('(').map(lambda x: x[0])

In [10]:
df['Winning_team'] = df['Winning_team'].str.split('won').map(lambda x: x[0])

In [16]:
df[df['Winning_team'] == 'Match tied (KKR ']

Empty DataFrame
Columns: [Match_no, Date, Team1, Team2, Venue, Winning_team, Player_of_match, Player_of_match_total_impact, Top_scorer, Top_scorer_runs]
Index: []

In [12]:
df.loc[37, 'Winning_team'] = 'KKR(Won On Super Over)'

In [14]:
df['Date'] = pd.to_datetime(df['Date'].str.split('-').apply(lambda x: x[0]).str.strip())

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Match_no                      74 non-null     object
 1   Date                          74 non-null     object
 2   Team1                         74 non-null     object
 3   Team2                         74 non-null     object
 4   Venue                         74 non-null     object
 5   Winning_team                  74 non-null     object
 6   Player_of_match               74 non-null     object
 7   Player_of_match_total_impact  74 non-null     float64
 8   Top_scorer                    74 non-null     object
 9   Top_scorer_runs               74 non-null     float64
dtypes: float64(2), object(8)
memory usage: 5.9+ KB

In [ ]:
df.to_csv('match_data2.csv', index=False)

# Done

In [ ]:
pd.read_csv('match_data2.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Match_no                      74 non-null     object
 1   Date                          74 non-null     object
 2   Team1                         74 non-null     object
 3   Team2                         74 non-null     object
 4   Venue                         74 non-null     object
 5   Winning_team                  74 non-null     object
 6   Player_of_match               74 non-null     object
 7   Player_of_match_total_impact  74 non-null     float64
 8   Top_scorer                    74 non-null     object
 9   Top_scorer_runs               74 non-null     float64
dtypes: float64(2), object(8)
memory usage: 5.9+ KB

In [ ]:
pd.read_csv('match_data2.csv')

,Match_no,Date,Team1,Team2,Venue,Winning_team,Player_of_match,Player_of_match_total_impact,Top_scorer,Top_scorer_runs
0,1st Match,2026-03-28,SRH,RCB,"M Chinnaswamy Stadium, Bengaluru",RCB,Jacob Duffy,123.64,Ishan Kishan,80.0
1,2nd Match,2026-03-29,KKR,MI,"Wankhede Stadium, Mumbai",MI,Shardul Thakur,100.88,Ryan Rickelton,81.0
2,3rd Match,2026-03-30,CSK,RR,"Barsapara Cricket Stadium, Guwahati",RR,Nandre Burger,71.05,Vaibhav Sooryavanshi,52.0
3,4th Match,2026-03-31,GT,PBKS,Maharaja Yadavindra Singh International Cricke...,PBKS,Cooper Connolly,87.23,Cooper Connolly,72.0
4,5th Match,2026-04-01,LSG,DC,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,DC,Sameer Rizvi,88.41,Sameer Rizvi,70.0
...,...,...,...,...,...,...,...,...,...,...
69,70th Match,2026-05-24,DC,KKR,"Eden Gardens, Kolkata",DC,Kuldeep Yadav,91.99,Ajinkya Rahane,63.0
70,Qualifier 1,2026-05-26,RCB,GT,"Himachal Pradesh Cricket Association Stadium, ...",RCB,Rajat Patidar,110.94,Rajat Patidar,93.0
71,Eliminator,2026-05-27,RR,SRH,Maharaja Yadavindra Singh International Cricke...,RR,Vaibhav Sooryavanshi,198.38,Vaibhav Sooryavanshi,97.0
72,Qualifier 2,2026-05-29,RR,GT,Maharaja Yadavindra Singh International Cricke...,GT,Shubman Gill,109.62,Shubman Gill,104.0
73,Final,2026-05-31,GT,RCB,"Narendra Modi Stadium, Ahmedabad",RCB,Virat Kohli,91.76,Virat Kohli,75.0